/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0aa83cda (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// IMPORTANT: service role key must ONLY be used on the server (never in browser code).
if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY env vars.");
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await supabase.from("kv_store_0aa83cda").upsert({ key, value });
  if (error) throw new Error(error.message);
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await supabase
    .from("kv_store_0aa83cda")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) throw new Error(error.message);
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const { error } = await supabase.from("kv_store_0aa83cda").delete().eq("key", key);
  if (error) throw new Error(error.message);
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const rows = keys.map((k, i) => ({ key: k, value: values[i] }));
  const { error } = await supabase.from("kv_store_0aa83cda").upsert(rows);
  if (error) throw new Error(error.message);
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await supabase.from("kv_store_0aa83cda").select("key,value").in("key", keys);
  if (error) throw new Error(error.message);

  // return values in same order as keys
  const map = new Map((data ?? []).map((r: any) => [r.key, r.value]));
  return keys.map((k) => map.get(k));
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await supabase.from("kv_store_0aa83cda").delete().in("key", keys);
  if (error) throw new Error(error.message);
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await supabase
    .from("kv_store_0aa83cda")
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};
