/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ordrmuxghffafgixfqxq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZHJtdXhnaGZmYWZnaXhmcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3NDc2ODYsImV4cCI6MjA4MTMyMzY4Nn0.ZLND8F4lH3P6BoM4yvycJ-XsE-iJdyo_E-GpgfuIk7M"